name: g1_deploy
dependencies:
  - python=3.11
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.7.0+cu128
      - torchvision==0.22.0+cu128
      - torchaudio==2.7.0+cu128
      - mujoco==3.2.6
      - numpy
      - pyyaml
      - glfw
      - onnx
      - onnxruntime
      - onnxscript
      - argparse
      - rsl-rl-lib==2.3.1
      - gymnasium==0.29.1
